//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVX.Live.CommServices.IVXWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://15.25.67.35:9001/BocomMatchService.wsdl", ConfigurationName="IVXWebService.matchservicePortType")]
    public interface matchservicePortType {
        
        // CODEGEN: 命名空间 http://15.25.67.35:9001/BocomMatchService.wsdl 的元素名称 strReqType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IVX.Live.CommServices.IVXWebService.MatchServiceReqResponse MatchServiceReq(IVX.Live.CommServices.IVXWebService.MatchServiceReqRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchServiceReqRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MatchServiceReq", Namespace="http://15.25.67.35:9001/BocomMatchService.wsdl", Order=0)]
        public IVX.Live.CommServices.IVXWebService.MatchServiceReqRequestBody Body;
        
        public MatchServiceReqRequest() {
        }
        
        public MatchServiceReqRequest(IVX.Live.CommServices.IVXWebService.MatchServiceReqRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://15.25.67.35:9001/BocomMatchService.wsdl")]
    public partial class MatchServiceReqRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strReqType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strReq;
        
        public MatchServiceReqRequestBody() {
        }
        
        public MatchServiceReqRequestBody(string strReqType, string strReq) {
            this.strReqType = strReqType;
            this.strReq = strReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchServiceReqResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MatchServiceReqResponse", Namespace="http://15.25.67.35:9001/BocomMatchService.wsdl", Order=0)]
        public IVX.Live.CommServices.IVXWebService.MatchServiceReqResponseBody Body;
        
        public MatchServiceReqResponse() {
        }
        
        public MatchServiceReqResponse(IVX.Live.CommServices.IVXWebService.MatchServiceReqResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://15.25.67.35:9001/BocomMatchService.wsdl")]
    public partial class MatchServiceReqResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strRsp;
        
        public MatchServiceReqResponseBody() {
        }
        
        public MatchServiceReqResponseBody(string strRsp) {
            this.strRsp = strRsp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface matchservicePortTypeChannel : IVX.Live.CommServices.IVXWebService.matchservicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class matchservicePortTypeClient : System.ServiceModel.ClientBase<IVX.Live.CommServices.IVXWebService.matchservicePortType>, IVX.Live.CommServices.IVXWebService.matchservicePortType {
        
        public matchservicePortTypeClient() {
        }
        
        public matchservicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public matchservicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public matchservicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public matchservicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IVX.Live.CommServices.IVXWebService.MatchServiceReqResponse IVX.Live.CommServices.IVXWebService.matchservicePortType.MatchServiceReq(IVX.Live.CommServices.IVXWebService.MatchServiceReqRequest request) {
            return base.Channel.MatchServiceReq(request);
        }
        
        public string MatchServiceReq(string strReqType, string strReq) {
            IVX.Live.CommServices.IVXWebService.MatchServiceReqRequest inValue = new IVX.Live.CommServices.IVXWebService.MatchServiceReqRequest();
            inValue.Body = new IVX.Live.CommServices.IVXWebService.MatchServiceReqRequestBody();
            inValue.Body.strReqType = strReqType;
            inValue.Body.strReq = strReq;
            IVX.Live.CommServices.IVXWebService.MatchServiceReqResponse retVal = ((IVX.Live.CommServices.IVXWebService.matchservicePortType)(this)).MatchServiceReq(inValue);
            return retVal.Body.strRsp;
        }
    }
}
